### ISSUE TITLE
Node cannot run, apphash inconsistent error

### ISSUE THREAD

**Issue by mayong82** [bnb-chain/node-binary#328]
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 4AAE7532B66BCFA9A6AB47F71CA028E44988B84DB6BC74B46EBD928C723D09FC, got FD2BAEC2F45ECEE87661B75F7E24EC8E1665FD3B4A736359A8DD4C74B32622E3

After upgrading to version 0.9.0, restart or prompt this.
Then use state_recover program recovers to the first 1000 heights, and this error will be prompted after a while after restart

 **./state_recover 234559000 /root/.bnbchaind/**
recover home_path[/root/.bnbchaind/] to height[234559000]
recover success

 **./bnbchaind start --home /root/.bnbchaind/**
panic: Failed to process committed block (234560001:F3B0C53C3A694905B0FC50D924498FB7606DC56736A1EE92C4D51E3BA3E658E3): Wrong Block.Header.AppHash.  Expected 4AAE7532B66BCFA9A6AB47F71CA028E44988B84DB6BC74B46EBD928C723D09FC, got FD2BAEC2F45ECEE87661B75F7E24EC8E1665FD3B4A736359A8DD4C74B32622E3

goroutine 519765 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00015a820)
        /root/workspace/workspace_go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.6/blockchain/v0/reactor.go:404 +0x1aa5
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/workspace/workspace_go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.6/blockchain/v0/reactor.go:127 +0x87

How to solve this problem?

**Comment by txsdev** [comment]
we got same problem and looking forward to solving the problem

**Comment by nrazavi70** [comment]
We are currently experiencing the exact same issue which happened on all our nodes at once

**Comment by butterfly-sn** [comment]
we got same problem and looking forward to solving the problem

**Comment by butterfly-sn** [comment]
I found the reason, there is a hard fork, here is the link @txsdev @nrazavi70 
https://www.bnbchain.world/en/blog/bnb-beacon-chain-mainnet-descartes-upgrade-announcement/

**Comment by mayong82** [comment]
According to the document, the problem has been solved.
https://www.bnbchain.world/en/blog/bnb-beacon-chain-mainnet-descartes-upgrade-announcement/
