### ISSUE TITLE
error during handshake: error on replay: Wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by MatheusMorozetti** [bnb-chain/node-binary#345]
I'm running BNB in this version: 

Binance Chain Release: v0.9.0;Binance Chain Commit: 255f572f; Cosmos Release: v0.25.0-binance.26; Tendermint Release: v0.32.3-binance.6;

And I got this error on block: 284376000

´´´Replay last block using real app             module=consensus 
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 77BAD6135E3FA487C7FBDA8EF56076B3CFBE5E9398D14C867F467A812E2C437E, got 4DFE3D526DFFEE7CF0DC2664091966FB0E6581EF7FED8595829AE642696BE44A
´´´

Is there a solution for this? I thought this error occurs for non-updated nodes, but I'm running the latest version

**Comment by isaacyuno** [comment]
Hi there, please use this release https://github.com/bnb-chain/node/releases/tag/v0.10.3

**Comment by MatheusMorozetti** [comment]
Thanks mate!, The problem was solved
