### ISSUE TITLE
ERROR: Block.Header.AppHash on mainnet with binary version 0.9.0

### ISSUE THREAD

**Issue by huanlv94** [bnb-chain/node-binary#346]
Hello everyone, today my fullnode stopped working with error:
```panic: Failed to process committed block (285075852:2BDC391C402FF452B83AD484D5C40DA615133C25E60C07352CBC6E45435EA873): Wrong Block.Header.AppHash.  Expected 3E60F1573122DC7FAD2C5E4779A21BFEEB578422C915A16DEA70A1A617314720, got 1EDDADB1DC0B8E67A3F10FCE05201A4A59A7C380EC54F3CA83D400317CC49685```

- Block number: 285075850

I tried running state_recover but it still stops at block 285075850. Has anyone encountered this situation? Please help.

**Comment by isaacyuno** [comment]
Hi there, which version do you use? https://github.com/bnb-chain/node/releases/tag/v0.10.3?

**Comment by huanlv94** [comment]
> Hi there, which version do you use? https://github.com/bnb-chain/node/releases/tag/v0.10.3?

Oh thank you, I'm missed this upgrade.
