### ISSUE TITLE
Unable to sync mainnet, failed to process committed block 285461516, state_recover do not work

### ISSUE THREAD

**Issue by technologiespro** [bnb-chain/node-binary#347]
Unable to sync mainnet, nothing helps:
bnbchaind v0.9.0

1. './state_recover 285461515 /home/mainnet/.bnbchaind' - recover success
2. syncing from scratch doesn't help either
3. always a error -  panic: failed to process committed block (285461516:B5CF8A19B231AF556E8B358B4019384E415E58523D62DFD1CD23873D3764132D): Wrong Block.Header.AppHash.  Expected 61A513D5D93184FA6A5A09CE3786DF9356545D4FFBC15DA36A335899B5B49718, got D2257A20C881CD9DBF3400E7B15A360F292E3E654EA88E6D0CE35218A1A75FDB

df -h '/dev/md0p2      3,7T  665G  2,9T  19% /' (nvme)

config https://github.com/bnb-chain/node-binary/blob/master/fullnode/prod/0.9.0/config/config.toml
app.toml https://github.com/bnb-chain/node-binary/blob/master/fullnode/prod/0.9.0/config/app.toml
genesis https://github.com/bnb-chain/node-binary/blob/master/fullnode/prod/0.9.0/config/genesis.json

does anyone know how to solve the problem?

**Comment by isaacyuno** [comment]
Please use latest version https://github.com/bnb-chain/node/releases/tag/v0.10.3

**Comment by technologiespro** [comment]
> Please use latest version https://github.com/bnb-chain/node/releases/tag/v0.10.3

wow, you made my day, thanks!
